name: Build and deploy Docker image

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build-and-push:
    name: Push to docker hub
    runs-on: ubuntu-latest
    environment: keys
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mewapewa/projects
          tags: portfolio

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  pull-on-remote:
    name: Pull from server
    runs-on: ubuntu-latest
    environment: keys
    needs: build-and-push
    steps:
      - name: call webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://docker-puller.memw.es/?image=mewapewa%2Fprojects%3Aportfolio
          method: POST
          customHeaders: '{
            "Auth": "${{ secrets.PULLER_KEY }}", 
            "Secrets": "API_GITHUB_TOKEN=${{ secrets.API_GITHUB_TOKEN }}"
          }'
