name: Build and deploy Docker image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-push-and-pull:
    name: Build, Push and Pull on remote
    runs-on: ubuntu-latest
    environment: keys
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mewapewa/projects
          tags: portfolio

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: "ApiGithubToken=${{ secrets.API_GITHUB_TOKEN }}"

      - name: Pull from remote
        if: success()
        run: |
          curl -X POST -H 'Auth: ${{ secrets.PULLER_KEY }}' \
          https://docker-puller.memw.es/?image=mewapewa%2Fprojects%3Aportfolio&ports=10001%3A10001